Adición de la chocolatina
eafit-devops/react-table pull request #2
Opened 2022-11-02 23:52 UTC by nassao

2022-11-02 23:56 UTC, LEO2706 requested changes

2022-11-02 23:56 UTC, LEO2706 commented on src/App.js
> +  createData('Chocolatina Hersheys', 250, 17.0, 40, 2.5),
Revisar las calorias

2022-11-02 23:56 UTC, cccarmonal requested changes

2022-11-02 23:56 UTC, cccarmonal commented on src/App.js
> +  createData('Chocolatina Hersheys', 250, 17.0, 40, 2.5),
Revisar las calorías

2022-11-03 00:03 UTC, nassao commented on src/App.js
> +  createData('Chocolatina Hersheys', 250, 17.0, 40, 2.5),
Resuelto

2022-11-03 00:04 UTC, LEO2706 approved these changes
Aprobado

2022-11-03 00:05 UTC, cccarmonal approved these changes

2022-11-03 00:07 UTC, nassao commented
Aprobado!

2022-11-03 00:08 UTC, merged